# Generated by Django 3.0.14 on 2021-09-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20210916_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0002_auto_20210916_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)'),
        ),
        migrations.AlterUniqueTogether(
            name='stghealthfacility',
            unique_together={('type', 'location', 'owner', 'name')},
        ),
    ]
