# Generated by Django 3.0.14 on 2021-09-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20210923_2033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityserviceprovision',
            unique_together={('domain', 'facility', 'units', 'date_assessed')},
        ),
    ]
