# Generated by Django 3.0.14 on 2021-12-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20210923_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
    ]
