# Generated by Django 3.0.14 on 2021-08-26 06:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import indicators.models
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aho_factsindicator_archive',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('value_received', models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='Value')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value')),
                ('start_period', models.IntegerField(default=2021, help_text='This Year marks the start of the reporting period', verbose_name='Starting Period')),
                ('end_period', models.IntegerField(default=2021, help_text='This Year marks the end of reporting.         The value must be current year or greater than the start year', verbose_name='Ending Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Indicators Archive',
                'db_table': 'fact_data_archive',
                'ordering': ('indicator__translations__name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AhoDoamain_Lookup',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=500, verbose_name='Indicator Name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Indicator Code')),
                ('domain_name', models.CharField(blank=True, max_length=230, verbose_name='Theme')),
                ('domain_level', models.IntegerField(verbose_name='Theme Level')),
            ],
            options={
                'verbose_name': 'Theme Lookup',
                'verbose_name_plural': 'Themes Lookup',
                'db_table': 'aho_domain_lookup',
                'ordering': ('indicator_name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgIndicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('afrocode', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Regional Code')),
                ('gen_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Global Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': '  Indicators',
                'db_table': 'stg_indicator',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorDomain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Theme Level')),
                ('code', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicators', models.ManyToManyField(blank=True, db_table='stg_indicator_domain_members', to='indicators.StgIndicator', verbose_name='Indicators')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Parent Theme')),
            ],
            options={
                'verbose_name': 'Indicator Theme',
                'verbose_name_plural': ' Indicator Themes',
                'db_table': 'stg_indicator_domain',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorReference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Indicator Reference',
                'verbose_name_plural': 'Indicator References',
                'db_table': 'stg_indicator_reference',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgNarrative_Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Narrative Type',
                'verbose_name_plural': 'Narrative Types',
                'db_table': 'stg_narrative_type',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IndicatorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Grid Form',
                'verbose_name_plural': '   Multi-records Grid',
                'managed': False,
                'proxy': True,
            },
            bases=('indicators.stgindicator',),
        ),
        migrations.CreateModel(
            name='StgIndicatorNarrative',
            fields=[
                ('indicatornarrative_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('narrative_text', models.TextField(verbose_name='Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
                ('narrative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type')),
            ],
            options={
                'verbose_name': 'Indicator Narrative',
                'verbose_name_plural': 'Indicators Narrative',
                'db_table': 'stg_indicator_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stgindicator',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorReference', verbose_name='Indicator Reference'),
        ),
        migrations.CreateModel(
            name='StgAnalyticsNarrative',
            fields=[
                ('analyticstext_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('narrative_text', models.TextField(verbose_name='Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Theme')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
                ('narrative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type')),
            ],
            options={
                'verbose_name': 'Theme Narrative',
                'verbose_name_plural': 'Theme Narratives',
                'db_table': 'stg_analytics_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgNarrative_TypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('shortname', models.CharField(max_length=120, null=True, unique=True, verbose_name='Short Name')),
                ('description', models.TextField(null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgNarrative_Type')),
            ],
            options={
                'verbose_name': 'Narrative Type Translation',
                'db_table': 'stg_narrative_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Indicator Name')),
                ('shortname', models.CharField(max_length=120, null=True, unique=True, verbose_name='Short Name')),
                ('definition', models.TextField(null=True, verbose_name='Indicator Definition')),
                ('preferred_datasources', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Primary Sources')),
                ('numerator_description', models.TextField(blank=True, null=True, verbose_name='Numerator Description')),
                ('denominator_description', models.TextField(blank=True, null=True, verbose_name='Denominator Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicator')),
            ],
            options={
                'verbose_name': 'Indicator Translation',
                'db_table': 'stg_indicator_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorReferenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='Global List of 100 Core Health Indicators', max_length=230, verbose_name='Reference Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicatorReference')),
            ],
            options={
                'verbose_name': 'Indicator Reference Translation',
                'db_table': 'stg_indicator_reference_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorDomainTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Theme')),
                ('shortname', models.CharField(max_length=45, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicatorDomain')),
            ],
            options={
                'verbose_name': 'Indicator Theme Translation',
                'db_table': 'stg_indicator_domain_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactDataIndicator',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value')),
                ('start_period', models.PositiveIntegerField(default=2021, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Starting period')),
                ('end_period', models.PositiveIntegerField(default=2021, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Ending Period')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categoryoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Options')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgDatasource', verbose_name='Data Source')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name')),
                ('measuremethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            options={
                'verbose_name': 'Indicator Data Record',
                'verbose_name_plural': '    Single-record Form',
                'db_table': 'fact_data_indicators',
                'ordering': ('indicator__translations__name',),
                'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')),
                'managed': True,
                'unique_together': {('indicator', 'location', 'categoryoption', 'datasource', 'start_period', 'end_period')},
            },
        ),
    ]
