# Generated by Django 3.0.14 on 2021-10-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0002_auto_20210929_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
        migrations.AlterField(
            model_name='stgindicator',
            name='afrocode',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Indicator Code'),
        ),
        migrations.AlterField(
            model_name='stgindicator',
            name='gen_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Standard Code'),
        ),
    ]
