# Generated by Django 3.0.14 on 2022-03-26 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import indicators.models
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20210916_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_stgcustomnationalobservatory_stgcustomnationalobservatorytranslation'),
        ('indicators', '0003_auto_20211012_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHOCustomizationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Customization Form',
                'verbose_name_plural': '    Customization Form',
                'managed': False,
                'proxy': True,
            },
            bases=('regions.stglocation',),
        ),
        migrations.CreateModel(
            name='NHOCustomizationIcons',
            fields=[
                ('icon_id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.CharField(max_length=5, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('version', models.CharField(blank=True, default='v5.15', max_length=15, null=True, verbose_name='Icon Version')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Custom Icon',
                'verbose_name_plural': 'Custom Icons',
                'db_table': 'stg_fontawesome_icons',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='end_period',
            field=models.PositiveIntegerField(default=2022, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='start_period',
            field=models.PositiveIntegerField(default=2022, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Starting period'),
        ),
        migrations.CreateModel(
            name='NHOCustomizationIconsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Title')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.NHOCustomizationIcons')),
            ],
            options={
                'verbose_name': 'Custom Icon Translation',
                'db_table': 'stg_fontawesome_icons_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NHOCustomFactsindicator',
            fields=[
                ('fact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='indicators.FactDataIndicator')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('value_received', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Value')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('priority', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Priority Level')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categoryoption', models.ForeignKey(default=99, on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Option')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgDatasource', verbose_name='Data Source')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.NHOCustomizationIcons', verbose_name='Font Icon')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name')),
                ('measuremethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            options={
                'verbose_name': 'Indicator Priority',
                'verbose_name_plural': 'Indicators Priorities',
                'db_table': 'fact_priority_indicators',
                'ordering': ('indicator__translations__name',),
                'managed': True,
                'unique_together': {('indicator', 'location', 'categoryoption', 'datasource', 'period')},
            },
        ),
    ]
