# Generated by Django 3.0.14 on 2022-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20220410_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhocustomfactsindicator',
            old_name='fact',
            new_name='fact_id',
        ),
    ]
