# Generated by Django 3.0.14 on 2023-01-24 07:19

import django.core.validators
from django.db import migrations, models
import indicators.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20220410_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdataindicator',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Dashboard Priority?'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='end_period',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='start_period',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Starting period'),
        ),
    ]
