# Generated by Django 3.0.14 on 2021-10-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0003_auto_20211012_1014'),
        ('home', '0007_auto_20211014_2127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0002_auto_20210916_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthServicesIndicatorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Multi-Form',
                'verbose_name_plural': '   Multi-Form',
                'managed': False,
                'proxy': True,
            },
            bases=('indicators.stgindicator',),
        ),
        migrations.CreateModel(
            name='HealthServices_DataIndicators',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value')),
                ('has_lastdate', models.BooleanField(default=False, verbose_name='Show End Date?')),
                ('start_period', models.DateField(default=django.utils.timezone.now, help_text='Start of reporting Period', verbose_name='Starting Date')),
                ('end_period', models.DateField(default=django.utils.timezone.now, help_text='End of reporting Period', verbose_name='Ending Date')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categoryoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Options')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgDatasource', verbose_name='Data Source')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name')),
                ('measuremethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgPeriodType', verbose_name='Periodicity Type')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': '    Single-Form',
                'db_table': 'fact_health_services',
                'ordering': ('indicator__translations__name',),
                'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')),
                'managed': True,
                'unique_together': {('indicator', 'location', 'categoryoption', 'datasource', 'start_period', 'end_period')},
            },
        ),
    ]
