# Generated by Django 3.0.14 on 2021-10-14 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservices_dataindicators',
            name='end_period',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='End of reporting Period', null=True, verbose_name='Ending Date'),
        ),
    ]
