# Generated by Django 3.0.14 on 2021-10-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211015_0556'),
        ('health_services', '0002_auto_20211014_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthservices_dataindicators',
            options={'managed': True, 'ordering': ('indicator__translations__name',), 'permissions': (('approve_facthealthservices', 'Can approve Health Services Data'), ('reject_facthealthservices', 'Can reject Health Services Data'), ('pend_facthealthservices', 'Can pend Health Services Data')), 'verbose_name': 'Health Record', 'verbose_name_plural': '    Single-Form'},
        ),
        migrations.AlterField(
            model_name='healthservices_dataindicators',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgPeriodType', verbose_name='Reporting Periodicity'),
        ),
    ]
