# Generated by Django 3.0.14 on 2021-10-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211015_0556'),
        ('indicators', '0003_auto_20211012_1014'),
        ('health_services', '0004_auto_20211016_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthServicesDomainsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': '  Programmes',
                'managed': False,
                'proxy': True,
            },
            bases=('indicators.stgindicatordomain',),
        ),
        migrations.CreateModel(
            name='HealthServicesIndicators',
            fields=[
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': '  Indicators',
                'managed': False,
                'proxy': True,
            },
            bases=('indicators.stgindicator',),
        ),
        migrations.AlterField(
            model_name='healthservices_dataindicators',
            name='periodicity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.StgPeriodType', verbose_name='Reporting Periodicity'),
        ),
        migrations.AlterField(
            model_name='healthservices_dataindicators',
            name='value_calculated',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=20, null=True, verbose_name='Calculated Value'),
        ),
        migrations.AlterField(
            model_name='healthservices_dataindicators',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Data Value'),
        ),
    ]
