# Generated by Django 3.0.14 on 2021-11-02 06:53

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20211012_1014'),
        ('health_services', '0005_auto_20211024_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthServicesProgrammes',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='Level')),
                ('code', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicators', models.ManyToManyField(blank=True, db_table='stg_health_service_indicators', to='indicators.StgIndicator', verbose_name='HSC Indicators')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='health_services.HealthServicesProgrammes', verbose_name='Main Programme')),
            ],
            options={
                'verbose_name': 'Indicator Program',
                'verbose_name_plural': ' Indicator Programs',
                'db_table': 'stg_health_continuity_programs',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HealthServicesProgrammesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Programme')),
                ('shortname', models.CharField(max_length=45, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health_services.HealthServicesProgrammes')),
            ],
            options={
                'verbose_name': 'Indicator Program Translation',
                'db_table': 'stg_health_continuity_programs_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='HealthServicesDomainsProxy',
        ),
    ]
