# Generated by Django 3.0.14 on 2021-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_services', '0006_auto_20211102_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthservicesindicators',
            options={'managed': False, 'verbose_name': 'HSC Indicator', 'verbose_name_plural': ' HSC Indicators'},
        ),
        migrations.AlterModelOptions(
            name='healthservicesprogrammes',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'HSC Programme', 'verbose_name_plural': ' HSC Programmes'},
        ),
        migrations.AlterModelOptions(
            name='healthservicesprogrammestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'HSC Programme Translation'},
        ),
        migrations.AlterField(
            model_name='healthservicesprogrammes',
            name='indicators',
            field=models.ManyToManyField(blank=True, db_table='stg_health_service_indicators', to='health_services.HealthServicesIndicators', verbose_name='HSC Indicators'),
        ),
    ]
