# Generated by Django 3.0.14 on 2021-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20211012_1014'),
        ('health_services', '0007_auto_20211102_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservicesprogrammes',
            name='indicators',
            field=models.ManyToManyField(blank=True, db_table='stg_health_service_indicators', to='indicators.StgIndicator', verbose_name='HSC Indicators'),
        ),
    ]
