# Generated by Django 3.0.14 on 2021-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_services', '0009_auto_20211102_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthservices_dataindicators',
            options={'managed': True, 'ordering': ('indicator__translations__name',), 'permissions': (('approve_facthealthservices', 'Can approve Health Services Data'), ('reject_facthealthservices', 'Can reject Health Services Data'), ('pend_facthealthservices', 'Can pend Health Services Data')), 'verbose_name': 'Single Record', 'verbose_name_plural': '    Single-Record Form'},
        ),
        migrations.AlterModelOptions(
            name='healthservicesindicatorproxy',
            options={'managed': False, 'verbose_name': 'Multi-Records Form', 'verbose_name_plural': '   Multi-Records Form'},
        ),
        migrations.AlterField(
            model_name='healthservicesprogrammes',
            name='indicators',
            field=models.ManyToManyField(blank=True, db_table='stg_health_cintinuity_indicators', to='health_services.HealthServicesIndicators', verbose_name='HSC Indicators'),
        ),
    ]
