# Generated by Django 3.0.14 on 2021-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_services', '0010_auto_20211102_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservicesprogrammes',
            name='indicators',
            field=models.ManyToManyField(blank=True, db_table='stg_health_continuity_indicators', to='health_services.HealthServicesIndicators', verbose_name='HSC Indicators'),
        ),
    ]
