# Generated by Django 3.0.14 on 2021-11-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_services', '0011_auto_20211102_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCPrograms_Lookup',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=500, verbose_name='HSC Indicator')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Indicator Code')),
                ('program_name', models.CharField(blank=True, max_length=230, verbose_name='HSC Programme')),
                ('level', models.IntegerField(verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Programs Lookup',
                'verbose_name_plural': 'Programs Lookup',
                'db_table': 'vw_hsc_indicators_lookup',
                'ordering': ('indicator_name',),
                'managed': False,
            },
        ),
    ]
