# Generated by Django 3.0.14 on 2021-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_urlsource'),
        ('regions', '0001_initial'),
        ('health_workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stghealthworkforcefacts',
            unique_together={('cadre', 'location', 'categoryoption', 'datasource', 'start_year', 'end_year')},
        ),
    ]
