# Generated by Django 3.0.14 on 2021-09-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('health_workforce', '0002_auto_20210916_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location'),
        ),
    ]
