# Generated by Django 3.0.14 on 2021-09-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0004_auto_20210923_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthworkforcefacts',
            options={'managed': True, 'ordering': ('cadre',), 'permissions': (('approve_stghealthworkforcefacts', 'Can approve Workforce Data'), ('pend_stghealthworkforcefacts', 'Can reject Workforce Data'), ('reject_stghealthworkforcefacts', 'Can pend Workforce Data')), 'verbose_name': 'Health Workforce', 'verbose_name_plural': '    Health Workforce'},
        ),
    ]
