# Generated by Django 3.0.14 on 2021-09-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20210916_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_workforce', '0005_auto_20210928_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgtraininginstitution',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
    ]
