# Generated by Django 3.0.14 on 2023-01-24 06:27

import django.core.validators
from django.db import migrations, models
import health_workforce.models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0007_auto_20211012_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgannouncements',
            name='end_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), health_workforce.models.max_value_current_year], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stgannouncements',
            name='start_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), health_workforce.models.max_value_current_year], verbose_name='Starting period'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='end_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='start_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), health_workforce.models.max_value_current_year], verbose_name='Starting period'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='end_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='start_year',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), health_workforce.models.max_value_current_year], verbose_name='Starting period'),
        ),
    ]
