# Generated by Django 3.0.14 on 2023-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0007_auto_20230124_1019'),
        ('regions', '0002_auto_20210916_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts_UHC_DatabaseView',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_id', models.PositiveIntegerField(blank=True, verbose_name='Indicator ID')),
                ('afrocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Indicator Code')),
                ('indicator', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Name')),
                ('location', models.CharField(max_length=500, verbose_name='Location Name')),
                ('categoryoption', models.CharField(max_length=500, verbose_name='Disaggregation Options')),
                ('datasource', models.CharField(max_length=500, verbose_name='Data Source')),
                ('measure_type', models.CharField(max_length=500, verbose_name='Measure Type')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value')),
                ('start_period', models.PositiveIntegerField(blank=True, verbose_name='Start Year')),
                ('end_period', models.PositiveIntegerField(blank=True, verbose_name='End Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('uhclock_theme', models.CharField(blank=True, max_length=150, verbose_name='UHC Clock Theme')),
                ('comment', models.CharField(blank=True, max_length=25, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'UHC Clock Fact',
                'verbose_name_plural': '   UHC Clock Facts',
                'db_table': 'vw_uhc_fact_data_indicators',
                'ordering': ('indicator',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgUHClockIndicatorsGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'UHC Clock Indicator Group',
                'verbose_name_plural': '  UHC Clock Indicator Groups',
                'db_table': 'stg_uhclock_indicator_groups',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgUHClockIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indicator_type', models.CharField(choices=[('1', 'Input'), ('2', 'Process'), ('3', 'Output'), ('4', 'Outcomes'), ('5', 'Impact')], default='1', max_length=5, verbose_name='Indicator Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHClockIndicatorsGroup', verbose_name='Indicator Group')),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
            ],
            options={
                'verbose_name': 'UHC Clock Indicator',
                'verbose_name_plural': '   UHC Clock Indicators',
                'db_table': 'stg_uhclock_indicators',
                'ordering': ('indicator',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgUHCIndicatorTheme',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2')], default=1, verbose_name='Theme Level')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHClockIndicatorsGroup', verbose_name='UHC Indicator Group')),
                ('indicators', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='group', chained_model_field='group', horizontal=True, limit_choices_to={'indicator__translations__language_code': 'en'}, to='uhc_clock.StgUHClockIndicators', verbose_name='indicators')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHCIndicatorTheme', verbose_name='Parent Theme')),
            ],
            options={
                'verbose_name': 'UHC Theme',
                'verbose_name_plural': '  UHC Clock Themes',
                'db_table': 'stg_uhclock_indicator_themes',
                'ordering': ('level',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountrySelectionUHCIndicators',
            fields=[
                ('countrychoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.ManyToManyField(default=None, to='uhc_clock.StgUHCIndicatorTheme', verbose_name='UHC Clock Theme')),
                ('indicators', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='domain', chained_model_field='group', horizontal=True, limit_choices_to={'indicator__translations__language_code': 'en'}, to='uhc_clock.StgUHClockIndicators')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Country/Location')),
            ],
            options={
                'verbose_name': 'Country Selection',
                'verbose_name_plural': 'UHC Clock Country Selections',
                'db_table': 'stg_uhclock_country_indicators_selection',
                'ordering': ('location',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgUHClockIndicatorsGroupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='Day [Health Impact and Outcome]', max_length=230, verbose_name='Reference Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='uhc_clock.StgUHClockIndicatorsGroup')),
            ],
            options={
                'verbose_name': 'UHC Clock Indicator Group Translation',
                'db_table': 'stg_uhclock_indicator_groups_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgUHCIndicatorThemeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Theme Name')),
                ('shortname', models.CharField(max_length=45, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='uhc_clock.StgUHCIndicatorTheme')),
            ],
            options={
                'verbose_name': 'UHC Theme Translation',
                'db_table': 'stg_uhclock_indicator_themes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
