# Generated by Django 3.0.14 on 2021-09-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210826_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='roles_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_admin', to=settings.AUTH_USER_MODEL, verbose_name='Logged Admin'),
        ),
    ]
