# Generated by Django 3.0.14 on 2021-08-26 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('data_wizard', '0002_filesource_urlsource'),
        ('regions', '0001_initial'),
        ('home', '0002_filesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLSource',
            fields=[
                ('urlsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_wizard.URLSource')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='home.FileSource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            bases=('data_wizard.urlsource',),
        ),
    ]
