# Generated by Django 3.0.14 on 2021-10-12 07:51

from django.db import migrations, models
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210930_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgPeriodType',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('name', models.CharField(default='Not Applicable', max_length=50, verbose_name='Period Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodicity',
                'verbose_name_plural': 'Period Types',
                'db_table': 'stg_time_period',
                'ordering': ('name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
