# Generated by Django 3.0.14 on 2021-10-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211014_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgperiodtype',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Period Type', 'verbose_name_plural': '   Period Types'},
        ),
        migrations.AddField(
            model_name='stgperiodtype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='stgperiodtype',
            name='date_lastupdated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgperiodtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Period Name'),
        ),
        migrations.AlterModelTable(
            name='stgperiodtype',
            table='stg_periodicity_type',
        ),
    ]
