# Generated by Django 3.0.14 on 2022-03-26 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20210916_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20211015_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgCustomNationalObservatory',
            fields=[
                ('observatory_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=45, unique=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Email')),
                ('phone_code', models.CharField(blank=True, help_text='The dialing code for a specific country e.g. +254 is         automatically assigned and combine with phone number as prefix.', max_length=5, verbose_name='Country Code')),
                ('phone_part', models.CharField(blank=True, help_text='Phone number must be numeric             value consisting of local area code without (0) prefix and the             specific line number.  For example: 788888888', max_length=15, validators=[django.core.validators.RegexValidator(message="Format:'999999999' min 8, maximum 15.", regex='^[0-9]{8,15}$')], verbose_name='Telephone Line')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number is the             combination of country code and telephone line, e.g.254788888888', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use correct phone number format', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telephone Number')),
                ('url', models.URLField(blank=True, max_length=2083, null=True, verbose_name='Web Address (URL)')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocationCodes', verbose_name='Country')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)')),
            ],
            options={
                'verbose_name': 'Customize Observatory',
                'verbose_name_plural': '   Customize Observatory',
                'db_table': 'stg_national_observatory',
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgCustomNationalObservatoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('custom_header', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Custom Header')),
                ('custom_footer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Custom Footer')),
                ('announcement', models.TextField(blank=True, null=True, verbose_name='Announcements')),
                ('coat_arms', models.ImageField(blank=True, null=True, upload_to='production/images/', verbose_name='Coat of Arms')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Physical Address')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.StgCustomNationalObservatory')),
            ],
            options={
                'verbose_name': 'Customize Observatory Translation',
                'db_table': 'stg_national_observatory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
