# Generated by Django 3.0.14 on 2022-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stgcustomnationalobservatory_stgcustomnationalobservatorytranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgcustomnationalobservatory',
            options={'managed': True, 'verbose_name': 'National Observatory', 'verbose_name_plural': '   National Observatory'},
        ),
        migrations.AlterModelOptions(
            name='stgcustomnationalobservatorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'National Observatory Translation'},
        ),
        migrations.AddField(
            model_name='stgcustomnationalobservatorytranslation',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='stgcustomnationalobservatorytranslation',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Observatory Title'),
        ),
    ]
