# Generated by Django 3.0.14 on 2023-01-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220326_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesource',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'File', 'verbose_name_plural': 'Import File...'},
        ),
        migrations.AlterModelOptions(
            name='urlsource',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'URL', 'verbose_name_plural': 'Import URL...'},
        ),
    ]
