# Generated by Django 3.0.14 on 2022-09-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('indicators', '0004_auto_20220903_1934'),
        # ('home', '0003_auto_20220918_1453'),
        ('data_quality', '0002_auto_20220920_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measuretypes_validator',
            unique_together={('indicator', 'measure_type')},
        ),
    ]
