# Generated by Django 3.0.14 on 2022-09-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('indicators', '0004_auto_20220903_1934'),
        # ('home', '0003_auto_20220918_1453'),
        ('data_quality', '0003_auto_20220921_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource_validator',
            unique_together={('indicator', 'datasource')},
        ),
    ]
