# Generated by Django 3.0.14 on 2022-09-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('home', '0003_auto_20220918_1453'),
        # ('indicators', '0004_auto_20220903_1934'),
        ('data_quality', '0004_auto_20220921_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryoptions_validator',
            unique_together={('indicator', 'categoryoption')},
        ),
    ]
