# Generated by Django 3.0.14 on 2022-09-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0005_auto_20220921_1130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dqaexternalconsistencyoutliersremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='dqainternalconsistencyoutliersremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='dqainvalidcategoryoptionremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='dqainvalidmeasuretyperemarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='dqainvalidperiodremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='dqavaluetypesconsistencyremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='mutiple_measuretypes',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
    ]
