# Generated by Django 3.0.14 on 2022-09-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0006_auto_20220921_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarity_index',
            unique_together={('source_indicator', 'similar_indicator')},
        ),
    ]
