# Generated by Django 3.0.14 on 2022-09-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_quality', '0007_auto_20220921_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingValuesRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Indicator Name')),
                ('location', models.CharField(blank=True, editable=False, max_length=2000, null=True, verbose_name='Country')),
                ('categoryoption', models.CharField(blank=True, editable=False, max_length=2000, null=True, verbose_name='category Option')),
                ('datasource', models.CharField(blank=True, editable=False, max_length=2000, null=True, verbose_name='Data Source')),
                ('measure_type', models.CharField(blank=True, editable=False, max_length=2000, null=True, verbose_name='Measure Type')),
                ('value', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=20, null=True, verbose_name='Value Received')),
                ('period', models.CharField(blank=True, editable=False, max_length=2000, null=True, verbose_name='Period')),
                ('counts', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Number of Measure Types')),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Remarks')),
                ('user', models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            options={
                'verbose_name': 'Missing Value',
                'verbose_name_plural': 'Missing Values',
                'db_table': 'dqa_missing_indicator_values',
                'ordering': ('indicator_name',),
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='MeasureType_Statistics',
        ),
    ]
