# Generated by Django 3.0.14 on 2022-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0008_auto_20220923_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingvaluesremarks',
            options={'managed': True, 'ordering': ('measure_type',), 'verbose_name': 'Missing Value', 'verbose_name_plural': 'Missing Values'},
        ),
        migrations.AlterUniqueTogether(
            name='missingvaluesremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
    ]
