# Generated by Django 3.0.14 on 2023-01-24 09:47

import data_quality.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0009_auto_20220925_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts_datafilter',
            name='end_period',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), data_quality.models.max_value_current_year], verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='facts_datafilter',
            name='start_period',
            field=models.PositiveIntegerField(default=2023, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), data_quality.models.max_value_current_year], verbose_name='Starting period'),
        ),
    ]
