# Generated by Django 3.0.14 on 2021-09-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stglocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='You are not allowed to edit this field because it is        related to other records', null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Parent Location'),
        ),
    ]
