# Generated by Django 3.0.14 on 2021-08-26 06:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import publications.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StgKnowledgeProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=45, unique=True)),
                ('internal_url', models.FileField(blank=True, upload_to='production/files/', verbose_name='File')),
                ('cover_image', models.ImageField(blank=True, upload_to='production/images/', verbose_name='Cover Picture')),
                ('external_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Knowledge Resource',
                'verbose_name_plural': '   Knowledge Resources',
                'db_table': 'stg_knowledge_product',
                'ordering': ('translations__title',),
                'permissions': (('approve_stgknowledgeproduct', 'Can approve stgknowledgeproduct'), ('reject_stgknowledgeproduct', 'Can reject stgknowledgeproduct'), ('pend_stgknowledgeproduct', 'Can pend stgknowledgeproduct')),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgProductDomain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Theme Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.StgProductDomain', verbose_name='Parent Theme')),
                ('publications', models.ManyToManyField(blank=True, db_table='stg_product_domain_members', to='publications.StgKnowledgeProduct', verbose_name='Resources')),
            ],
            options={
                'verbose_name': 'Resource Theme',
                'verbose_name_plural': '  Resource Themes',
                'db_table': 'stg_publication_domain',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgResourceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('category', models.SmallIntegerField(choices=[(1, 'Research Products'), (2, 'Health Workforce')], default=1, verbose_name='Classification')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': ' Resource Categories',
                'db_table': 'stg_resource_category',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgResourceType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': '  Resource Types',
                'db_table': 'stg_resource_type',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='categorization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='publications.StgResourceCategory', verbose_name='Resource Category'),
        ),
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Resource Location'),
        ),
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.StgResourceType', verbose_name='Resource Type'),
        ),
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
        migrations.CreateModel(
            name='StgResourceTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Type Name')),
                ('shortname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.StgResourceType')),
            ],
            options={
                'verbose_name': 'Resource Type Translation',
                'db_table': 'stg_resource_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgResourceCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Category Name')),
                ('shortname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.StgResourceCategory')),
            ],
            options={
                'verbose_name': 'Resource Category Translation',
                'db_table': 'stg_resource_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgProductDomainTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Resource Theme')),
                ('shortname', models.CharField(max_length=45, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Theme Level')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.StgProductDomain')),
            ],
            options={
                'verbose_name': 'Resource Theme Translation',
                'db_table': 'stg_publication_domain_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgKnowledgeResourceTagging',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Tagged To:')),
                ('publications', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.StgKnowledgeProduct', verbose_name='Resource Name')),
            ],
            options={
                'verbose_name': 'Resource Tag',
                'verbose_name_plural': 'Resource Tags',
                'db_table': 'stg_knowledge_resource_tag',
                'managed': True,
                'unique_together': {('publications', 'location')},
            },
        ),
        migrations.CreateModel(
            name='StgKnowledgeProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=2000, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract/Summary')),
                ('author', models.CharField(max_length=200, verbose_name='Author/Owner')),
                ('year_published', models.PositiveIntegerField(default=2021, help_text='This marks year of publication', validators=[django.core.validators.MinValueValidator(1900), publications.models.max_value_current_year], verbose_name='Year Published')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.StgKnowledgeProduct')),
            ],
            options={
                'verbose_name': 'Knowledge Resource Translation',
                'db_table': 'stg_knowledge_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
