# Generated by Django 3.0.14 on 2021-08-26 13:45

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgresourcecategory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category_type', to='publications.StgResourceType', verbose_name='Resource Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stgknowledgeproduct',
            name='categorization',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category_type', to='publications.StgResourceCategory', verbose_name='Resource Type'),
        ),
    ]
