# Generated by Django 3.0.14 on 2021-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210826_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgknowledgeproduct',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='stgknowledgeproduct',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='stgknowledgeproduct',
            name='internal_url',
        ),
        migrations.AddField(
            model_name='stgknowledgeproducttranslation',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='production/images/', verbose_name='Cover Picture'),
        ),
        migrations.AddField(
            model_name='stgknowledgeproducttranslation',
            name='external_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='stgknowledgeproducttranslation',
            name='internal_url',
            field=models.FileField(blank=True, upload_to='production/files/', verbose_name='File'),
        ),
    ]
