# Generated by Django 3.0.14 on 2021-09-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20210916_1203'),
        ('publications', '0005_auto_20210904_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgeresourcetagging',
            options={'managed': True, 'ordering': ('location__translations__name',), 'verbose_name': 'Resource Tag', 'verbose_name_plural': 'Resource Tags'},
        ),
        migrations.AlterField(
            model_name='stgknowledgeproduct',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Resource Location'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeresourcetagging',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Tagged To:'),
        ),
    ]
