# Generated by Django 3.0.14 on 2021-09-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20210916_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgeproduct',
            options={'managed': True, 'ordering': ('translations__title',), 'permissions': (('approve_stgknowledgeproduct', 'Can approve Knowledge Resource'), ('reject_stgknowledgeproduct', 'Can reject Knowledge Resource'), ('pend_stgknowledgeproduct', 'Can pend Knowledge Resource')), 'verbose_name': 'Knowledge Resource', 'verbose_name_plural': '   Knowledge Resources'},
        ),
    ]
