# Generated by Django 3.0.14 on 2023-01-24 06:30

import django.core.validators
from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20211012_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='year_published',
            field=models.PositiveIntegerField(default=2023, help_text='This marks year of publication', validators=[django.core.validators.MinValueValidator(1900), publications.models.max_value_current_year], verbose_name='Year Published'),
        ),
    ]
