# Generated by Django 3.0.14 on 2023-01-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20210928_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataelement',
            name='end_year',
            field=models.IntegerField(default=2023, verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='start_year',
            field=models.IntegerField(default=2023, verbose_name='Start Year'),
        ),
    ]
